sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
services:
  - docker
notifications:
  on_success: never
  on_failure: always
before_install:
  - nvm install 8
script: npm run test
after_script:
 - docker kill $(docker ps -q)